[package]
name = "blackcube-rs"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.9", features = ["json"] }
serde_json = "1.0.78"
mongodb = { version = "2.1.0", default-features = false, features = ["sync"] }
serde = "1.0.135"
toml = "0.8.8"
bson = "2.1.0"
anyhow = "1.0"
url = "2.5.0"
rust-s3 = "0.33.0"
mime = "0.3.17"
poise = "0.6.1"
image = "0.25.1"
