name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu

      # DEPRECATED
      - name: Build the second artifact
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu

      - name: List dirs and files
        run: ls -R

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BlackCube-rs Artifact
          path: |
            "./target/release/blackcube-rs"
            "./target/x86_64-pc-windows-gnu/release/blackcube-rs.exe"
