name: Update n Test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-n-test:
    name: Update n Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Update Rust
        run: rustup update

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump dependencies
        run: cargo upgrade

      - name: Update lockfile
        run: cargo update

      - name: Run clippy
        run: cargo clippy --all-features --all-targets

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: '[deps] bump'
          body: 'bump deps'
          commit-message: '[deps] bump'
