name: Bump deps

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump-deps:
    name: Bump deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Update Rust
        run: rustup update

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump dependencies
        run: cargo upgrade

      - name: Update lockfile
        run: cargo update

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: '[deps] bump'
          body: 'bump deps'
          commit-message: '[deps] bump'
          branch: 'bump-deps'
